# /home/deploy/apps/yueic-mall/docker-compose.yml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: yueic-mall:latest
    container_name: yueic-mall-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_SERVLET_CONTEXT_PATH=/mall   # 컨텍스트 경로
      - SERVER_PORT=8003                    # 내부 포트 (Spring이 8003 리슨)
    networks: [ web ]

  nginx:
    image: nginx:1.27-alpine
    container_name: yueic-mall-nginx
    depends_on: [ app ]
    ports:
      - "80:80"   # 포트 없이 http://yueic.duckdns.org 로 접속
      # 필요하면 추가: - "8003:80"
    volumes:
      - ./portal:/usr/share/nginx/html:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks: [ web ]

networks:
  web:
    driver: bridge
