spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://yueic.duckdns.org:8000/mydb?useSSL=false&serverTimezone=Asia/Seoul
    username: yueic
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8003
